### ISSUE TITLE
Configuration still marked as "dirty" after saving (sometimes)

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#121]
Steps to reproduce:

1. Start GPX Animator
2. Press button "Add Track"
3. Save the configuration
4. Close GPX Animator

Expected behavior: Closing without warning.
Actual behavior: A dialog warning of unsaved changes.

Strange: After the saving, if you move the mouse around the GPX Animator window to the close button, it closes as expected. But if you move directly over the GPX Animator windows to the close button, the dirty flag comes back to the window title and you get a warning message on closing.

Without changing anything. It looks like there may be something wrong with the change listeners. This behavior seems to be new, so it may be related to new configuration and track settings added to the actual version of GPX Animator.

**Comment by McPringle** [comment]
I have recognized that this happens when the mouse pointer moves over the *Enable Icon* option. Without clicking. Just moving. Must be an error regarding to one of the commits of issue #54.

**Comment by heroichornet** [comment]
@McPringle I couldn't reproduce at first using `jdk1.8.0_212` on OSX, I then built using `openjdk 11.0.4 2019-07-16` and ran under `OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu219.04)` and saw the error immediately.  As you suspected the problem was the listener. I copied the implementation of the checkbox in the `GeneralSettingsPanel`, should work , check out the latest pull request. Sorry about that
