### ISSUE TITLE
Movable map

### ISSUE THREAD

**Issue by PepaMB** [zdila/gpx-animator#13]
Bylo by možné, aby byl bod uprostřed obrazu pevný a posouvala se mapa? Něco jako v navigaci, jen 2D a sever nahoře. Díky

**Comment by zdila** [comment]
pozriem sa na to v niektorej z dalsich verzii

**Comment by PepaMB** [comment]
Cílem je možnost vytvořit video s pohybem v mapě, které bych vložil do reálného videa natáčeného cestou. Děkuji

**Comment by McPringle** [comment]
I don't understand Czech, so I used Google Translator to translate the comments shown above:

> @PepaMB: Would it be possible for a point in the center of the image to be fixed and move the map? Something like navigation, just 2D and north up. Thanks

> @zdila: I'll look at it in one of the other versions

> @PepaMB: The goal is to create a video with movement on the map, which I would embed in a real video shot on the road. Thank you

This issue is rather old but the idea sounds very interesting. I think it would be a nice feature for a new version of GPX Animator, but I have respect refactoring the whole rendering process to make this work.

**Comment by zdila** [comment]
I think this issue should be of high priority as it adds much for user experience.

**Comment by McPringle** [comment]
Five years after this issue was filed two really nice guys were able to implement such a feature with PR #251! Thank you very much, @thomergil and @RonaldBoer.
