### ISSUE TITLE
Skip the days that doesn't have data

### ISSUE THREAD

**Issue by systurbed** [zdila/gpx-animator#213]
Hello, I have been using gpx and is an amazing tool, I just have a doubt, can we skip the days that doesn't have data. I ask because when the animation is generated I have several days that I didn't rode my bicycle and they make the animation "slow" as the days pass without something happening in the map. Thank you again!!

**Comment by McPringle** [comment]
That should be done automatically if you activate "Skip Idle" on the "General" tab. If GPX Animator finds a part of the route with no movement, it will animate a "flash" (you can change this with the settings for "Flashback Color" and "Flashback Duration").

Here is an example: https://www.youtube.com/watch?v=SnN0tsyqRN8

Please try it out. If you have any problems, please provide the GPX file and the saved configuration (File > Save), so I can reproduce the problem. If you don't want to make your files public, you can send them to support@gpx-animator.app (please mention this issue here).

**Comment by systurbed** [comment]
Oooo I missed that option, thank you very much! I am eager for the next version. Thanks for the amazing work!
