### ISSUE TITLE
No attribution with video creation via command line

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#217]
**I found this problem in the version 1.6.0-SNAPSHOT. I guess, it is present in all previous versions, too.**

In the finally rendered video, the attribution in the lower left corner looks like:
```
Created with %APPNAME_VERSION%
%MAP_ATTRIBUTION%
```

I would expect the placeholders to be replaced correctly, like rendering the video using the GPX Animator GUI:

```
Created with GPX Animator 1.6.0-SNAPSHOT
© OpenStreetMap contributors, CC-BY-SA
```

To reproduce this error, use the command line rendering without the GUI:

```
java -jar build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input src/test/resources/gpx/bikeride.gpx --output test.mp4
```

**The test data included in the project is fine and can be used to reproduce the problem easily.**

A screenshot, how it looks like if you render the video using the command line only (German version):
<img width="176" alt="Bildschirmfoto 2020-10-05 um 11 09 39" src="https://user-images.githubusercontent.com/1254039/95060996-4c348380-06fb-11eb-80b7-dc8443c73850.png">

A screenshot, how it should look like (taken from a different video rendered using the GUI) (German version):
<img width="269" alt="Bildschirmfoto 2020-10-05 um 11 07 34" src="https://user-images.githubusercontent.com/1254039/95060806-0e375f80-06fb-11eb-9daa-bfaa416e2208.png">

**Comment by galz10** [comment]
I'm currently trying to fix this, the APPNAME_VERSION problem I fixed so no matter if you use the GUI or command line it populates, where I ran into a problem was the MAP_ATTRIBUTION. Since you don't provide a map then I don't know how it would get the attribution.

What I did was when you use the command line and you don't provide attribution in the command line (Like --attribution) it will render just the APPNAME_VERSION, if you provide an attribution it will render the provided attribution.

**Comment by McPringle** [comment]
Good morning @galz10 

That sounds like a good solution. The app name and version are always present, the map of course not. Just remove the placeholder (replace with nothing) so there will be no placeholder in the movie. Great!

Thank you very much for your work on this issue, I highly appreciate it.

**Comment by galz10** [comment]
I'll create a PR so we can close this issue

**Comment by galz10** [comment]
Here's the PR: https://github.com/zdila/gpx-animator/pull/226
