### ISSUE TITLE
A low `--tail-duration` value causes the dot to flicker

### ISSUE THREAD

**Issue by thomergil** [zdila/gpx-animator#286]
--tail-duration should affect the tail, not the dot. The line still gets drawn correctly, but without a dot.

**Comment by McPringle** [comment]
- With a value of 0, the dot is rarely visible.
- With a value of 1'000, the flicker effect is very good to recognize.
- With a value of 10'000, the dot is getting stable

Idea: Can this be related to not display the dot, when the driver stops driving for some time?

**Comment by thomergil** [comment]
By the way, I think hiding the dot during a pause is undesirable behavior. I think the dot should **always** be visible. The driver does not stop existing, even if they're taking a break. 😄 I know this is getting old, but if you really like hiding the dot, maybe make it configurable with `--hide-paused-dot` or something?

**Comment by McPringle** [comment]
This is just a guess of mine that the dot is not displayed when a break is detected. I would have to analyze that first, too.

**Comment by McPringle** [comment]
I can confirm, that the problem is *not* related to a pause or break. For every frame in the video, the marker is drawn. At least, the `drawMarker` method is called. The problem must be somewhere else and it looks like the missing marker is a side effect. Maybe it has to do with stacking drawings in layers? I'll continue investigating.
