### ISSUE TITLE
SOLVED - Position of photographs along track incorrect under some circumstances.

### ISSUE THREAD

**Issue by albansuser** [zdila/gpx-animator#320]
While experimenting with GPX Animator (1.6), the positions of photographs along the displayed track are incorrect under some circumstances.

**Functioning scenario**:
GPX track recorded on mobile phone (using OSMAnd) and photographs made with the mobile phone (not geo-referenced at the time).  

The photographs are subsequently geo-referenced correctly (locations checked) using Photo Mechanic.

The recorded track and the photographs are then loaded into GPX Animator and the appearance and location of the photographs are correct along the displayed track.

**Non-functioning scenario**:
GPX track recorded on mobile phone (again using OSMAnd) and photographs made with a dedicated camera (Fuji, again images not geo-referenced at the time).

The photographs are subsequently geo-referenced correctly (locations checked) using Photo Mechanic.

The recorded track and the photographs and then loaded into GPX Animator. The appearance and location of the photographs are incorrect. 

Only some of the photographs appear along the recorded track, and when they do they are in completely wrong locations.

Since the geo-reference tags for all photographs taken with both the mobile phone and camera are correct,  I’m wondering whether there is a timestamp issue. 

Is GPX animator using timestamps rather then geolocation to position photographs along the track?

It’s worth noting that when all the photographs were geo-referenced, time differences between the GPS stamp and the camera time stamp were properly taken into account. Hence the resultant correct  geo locations.

Is there a simple explanation for this?

Thank you.

Regards

**Comment by albansuser** [comment]
After a few more hours of experimenting, I discovered a -1 hour time offset was required in GPX Animator, in addition to the offset required when geo-referencing the original photos.

**Comment by McPringle** [comment]
Hi @albansuser 

I'm glad you solved it for your scenario. GPX Animator uses the timestamps of the photos to show them at the correct animation time. I decided to go with timestamps rather than the GEO location because most dedicated cameras are not recording a GPS signal. But all digital cameras record the date and time, the photo was taken. If the time settings from all of your devices are synched, you can just use the GPX track and the photos without third-party tools to add GEO information.

Using the GPS location would have some additional challenges, too: Two devices at the same place have very rarely the same GPS position. There are always differences. Would we use the GPS location of the photos, we would need to calculate kind of a circle around the position of the photo to get a match with the track. This would be much more inaccurate, which you would notice depending on the zoom level of the map.

A time difference of one hour could indicate an incorrectly set time zone of one of the two devices involved. Or you created the GPX file recording in one time zone and were in another when you created the video.

**Comment by albansuser** [comment]
Hello McPringle.

Thank you for the full explanation.

Appreciated.

Regards
