### ISSUE TITLE
Rendering multiple tracks results in extremely slow rendering

### ISSUE THREAD

**Issue by sn3akz** [zdila/gpx-animator#368]
When rendering 1 track, the render time per frame is constant and consistent.

When rendering 2 tracks, the render time worsens over time, up to minutes per frame, instead of a few seconds.

It looks like there is some non-linear complexity going on when having multiple tracks.

Attached the 2 tracks (with missing points) and the config file for GPX Animator

[Test.zip](https://github.com/zdila/gpx-animator/files/6858669/Test.zip)

**Comment by McPringle** [comment]
Thank you very much for your report and test data! I'm on a bike packing trip and will investigate your problem as soon, as I return (in about two to three weeks).

**Comment by McPringle** [comment]
Your problem is caused by hundreds of waypoints in your files! This is highly unusual. Displaying hundreds of waypoints on the map is cluttering the map, so you won't be able to see the track anymore. Usually you should have about five or at max ten waypoints in your files.

What do you want to achive with so many waypoints? Your map would be nearly fully black…

**Comment by McPringle** [comment]
Waypoints can have a date and time. If they have a date and time, they will not be shown from the beginning of the animation. They will occour at the specified date and time. For each frame rendered, GPX Animator has to check which waypoints must be shown. The more waypoints must be rendered on a frame, the more time is needed. This is the reason, why your GPX file rendering is slowing down over time. This is a technical requirement and can't be fixed.

My suggestion: Limit the number of waypoints. This will speed up the rendering process again and it will make the animation more clear (because there are less waypoints over the map).

**Comment by sn3akz** [comment]
AH!

Thank you, I think something must have gone wrong with converting the original data to GPX files. It was never my intention to have waypoints, let alone that many. My apologies for the faulty report and wasting your time chasing a non-existent bug.

Regards

**Comment by McPringle** [comment]
No problem – sometimes it is useful to have someone else take a look at the issue. It is never wasted time!

Instead of a list of waypoints, you should have a track in each of the two GPX files.

Example: https://raw.githubusercontent.com/zdila/gpx-animator/master/src/test/resources/gpx/bikeride.gpx

Which type is your original data? Maybe I can help to convert it correctly.

**Comment by sn3akz** [comment]
Thank you for the offer, but no need. Already was able to convert it properly. The original was KML data from fllightradar24.com
