### ISSUE TITLE
Error "org/joda/time/DateTime"

### ISSUE THREAD

**Issue by fidollus** [zdila/gpx-animator#88]
Every time I try to render, I get this error. What can I do?

THX
Fido

**Comment by McPringle** [comment]
Hi @fidollus, please excuse my late answer, I was on a sabbatical for a few months.

I downloaded your files and recognized, that you have used one of the *OpenStreetMap* background maps. OSM made a change to their webserver a few weeks ago, now they do a redirect from HTTP to HTTPS which GPX Animator can't handle. This is fixed in the pre-release version 1.4, which will be available before Xmas (hopefully). You can download this pre-release version from our website.

I have used this pre-release version with your files and rendering the video worked flawlessly. Can you please try version 1.4, too, and report to this issue, if it works for you or not?

Please download it here: https://gpx-animator.app/

**Comment by McPringle** [comment]
I analyzed the code further and this problem was solved with issue #47 by removing the JodaTime dependency. That's why I'm closing this issue now. You can wait for the next release of GPX Animator or you can download and use the snapshot version (beta quality) from the [GPX Animator Website](https://gpx-animator.app/). Thank you very much for your reports, @fidollus and @Steffens1950.

**Comment by Steffens1950** [comment]
Hi Marcus,

 

I tried today to work with the new version.

It is not working as you can see in the attached snapshot.

 

Do you have an idea what is my mistake?

 

Best regards

Peter

 

 

 



 

 

Von: Marcus Fihlon <notifications@github.com> 
Gesendet: Sonntag, 1. Dezember 2019 10:26
An: zdila/gpx-animator <gpx-animator@noreply.github.com>
Cc: Steffens1950 <pst1950@t-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [zdila/gpx-animator] Error "org/joda/time/DateTime" (#88)

 

Hi @fidollus <https://github.com/fidollus> , please excuse my late answer, I was on a sabbatical for a few months.

I downloaded your files and recognized, that you have used one of the OpenStreetMap background maps. OSM made a change to their webserver a few weeks ago, now they do a redirect from HTTP to HTTPS which GPX Animator can't handle. This is fixed in the pre-release version 1.4, which will be available before Xmas (hopefully). You can download this pre-release version from our website.

I have used this pre-release version with your files and rendering the video worked flawlessly. Can you please try version 1.4, too, and report to this issue, if it works for you or not?

Please download it here: https://gpx-animator.app/

**Comment by McPringle** [comment]
Hi @Steffens1950 

You answered to the email notification from GitHub that does not handle email attachments. Please open this issue in your browser to add an attachment. I am very interested in your issue to solve it.

**Comment by Steffens1950** [comment]
Here it comes.
Peter

![GPX Animator](https://user-images.githubusercontent.com/55182654/70388608-7373d480-19b4-11ea-8c42-565c6e6380a8.jpg)

**Comment by McPringle** [comment]
Hi @Steffens1950, thank you very much for the screenshot. That is a new error and does not belong to the problem of this issue. Can you please open a new issue and provide the GPX and the configuration (`*.ga.xml`) file, so I can try to reproduce your error?
