### ISSUE TITLE
Delete old map tile cache files on application startup

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#93]
PR #85 introduces a map tile cache based on files. Regarding the cleanup of the cache @n76 wrote:

> Looking at my cache directory, I think I need to handle the aging differently. At present I only age the files we are looking at. This means that if/when you finish making a video the cached tiles are likely to remain for a long time (until you make another animation that happens to use those same tiles).

I suggest adding a method to the `TileCache` class which scans the cached files and deletes the old ones. This method can be called on application shutdown and can show a short status update in the status bar, like "Cleaning up cache directory". Usually, this should only take a few milliseconds, so the user will hardly recognize a delay in closing the app.

**Comment by n76** [comment]
Might be a good idea to call a cache age method on both start up and shutdown.

I'd expect the cached map tiles would all be pretty recent when you are exiting the app, at least for the video(s) you've just made. But when you have some more tracks to animate a week or two later those tiles will now be stale.

The final pull request that was merged actually checks the cache for aged files every time a tile is requested. Despite that it is still so much faster than downloading the tile again.

I was thinking on rate limiting the cache clear/aging logic. Maybe call the cache age/clear on start up and then when requesting a tile if it has been longer than a few minutes since the last time the cache was aged.

**Comment by n76** [comment]
Thinking about this some more:

- Clear all old map tile files from the cache on start up.
- There should be some sanity checks so that if the user specifies a directory that also has other files we don't touch them. For example, we should only remove files where the names are exactly the correct length and that have a .png extension.
- When fetching a map tile from the cache, we can check that one file for being too old and refresh as needed.
This should limit the damage we do if the user specifies an inappropriate cache directory and should be fast and efficient for fetching map tiles when rendering.

If this seems appropriate, then I can have the changes available fairly soon.

**Comment by McPringle** [comment]
Instead of relying on the length of the name and the extension, we can use a *double extension* like `FOOBAR123XYZ.gpxac.png`. So it is easy to identify the caching files, GPX Animator created before. It is still double-clickable and will open an image viewer. `gpxac` is the abbreviation of GPX Animator Cache. What do you think?

**Comment by n76** [comment]
The more checks the better. I'll have a pull request up in a little bit that will incorporate gpxac into the suffix.

**Comment by McPringle** [comment]
Now I think it is better, to delete the old tiles at application startup, not shutdown, to start with a clean cache.

**Comment by n76** [comment]
At present the cache is cleared when the renderer is instantiated. That is not quite when the application is started, but before we actually use the cache for anything. If that is good enough then we can close this issue. If not, then point out where the call to `TileCache.ageCache()` should be put and I can submit a pull request.

**Comment by McPringle** [comment]
Hi @n76, I did the change and moved the method call to the `Main` class. Often I render a video a few times with different settings until I am satisfied. There is no need to check the whole cache on every rendering process. Well, it won't make the rendering recognizably slower, but now it "feels" better. :-)
